baseURL = "/doc-ds-staff/"
languageCode = "en-us"
title = "Documentation of Alumni Data Analytics Project for Office Assistants"
theme = "book"


[params]
    # (Optional, default light) Sets color theme: light, dark or auto.
    # Theme 'auto' switches between dark and light modes based on browser/os preferences
    BookTheme = 'auto'
    